### ISSUE TITLE
Suggestion: When the box opens, remove the top.

### ISSUE THREAD

**Issue by EsserGaming** [Jesus-QC/BetterDrops#2]
**When the box opens, remove the top of the box. As it usually covers the item and then you can't pick it up..
And an alternative to removing the top is to instead have the top blow off or make it move further away so it doesn't block the item.**

**Comment by Jesus-QC** [comment]
The latest release deletes all parts of the box 5 seconds after opening it, does that work for you?

**Comment by EsserGaming** [comment]
Sure!
