### ISSUE TITLE
NRE When Executing the MtfCommand

### ISSUE THREAD

**Issue by xNexusACS** [Jesus-QC/BetterDrops#5]
![image](https://user-images.githubusercontent.com/83370388/198394730-604ddb90-123d-4462-8f04-90463f5368b5.png)

**Comment by Jesus-QC** [comment]
@xNexus-ACS seems like your configs weren't parsed correctly. Not a plugin issue, however I can add checks for that

**Comment by xNexusACS** [comment]
interesting, well, if you can add checks will be good jesus

**Comment by Jesus-QC** [comment]
will do
